name: Home Assistant Config Check
on:
  push:
    branches:
      - master
    paths: 
      - 'hass/**'
      - '.github/**'
      - '.stubs/**'
  pull_request:

jobs:
  home_assistant_current:
    runs-on: ubuntu-latest
    steps:
      - name: Getting Home Assistant configuration
        uses: actions/checkout@v1
      #- name: Copy stub files into configuration folder
      #  run: cp -R ./.stubs/hass/* ./hass
      #- name: Read current Home Assistant version
      #  id: home_assistant_version
      #  uses: juliangruber/read-file-action@v1
      #  with:
      #    path: ./hass/.HA_VERSION
      #- name: Home Assistant Check
      #  uses: "docker://homeassistant/home-assistant:${{ steps.home_assistant_version.outputs.content }}"
      #  with:
      #    args: python -m homeassistant --config ./hass/ --script check_config --info all
