language: minimal

services:
  - docker
  
jobs:
  include:
    - name: Test Home Assistant config
      script:
        - |
            if [ "${TRAVIS_COMMIT_RANGE}" ] ; then
              git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qvE '(^(hass))/' && {
                echo "Home Assistant files were changed. Testing configuration..."
                export HA_VERSION="`cat $TRAVIS_BUILD_DIR/hass/.HA_VERSION`"
                touch $TRAVIS_BUILD_DIR/hass/FakeCertificate.pem
                touch $TRAVIS_BUILD_DIR/hass/FakeKey.pem
                mv $TRAVIS_BUILD_DIR/.travis_dummy/dummy_secrets.yaml hass/secrets.yaml
                mv $TRAVIS_BUILD_DIR/.travis_dummy/dummy_service_account.json hass/service_account.json
                docker pull homeassistant/home-assistant:$HA_VERSION
                docker run -v $TRAVIS_BUILD_DIR/hass:/config homeassistant/home-assistant:$HA_VERSION python -m homeassistant --config /config --script check_config --info all
              exit
            }
            fi
