language: python

services:
  - docker

before_install:
  - mkdir hass/certs
  - touch hass/certs/FakeKey.pem
  - mv .dummy_secrets.yaml hass/secrets.yaml
  - docker pull homeassistant/home-assistant:stable
  
script:
  - docker run homeassistant/home-assistant:stable ./hass:/config --script check_config --info all