language: python

services:
  - docker

before_install:
  - export HA_VERSION=foo="`cat $TRAVIS_BUILD_DIR/hass/HA_VERSION`"
  - echo "HELLO $SOME_VAR"
  #- touch $TRAVIS_BUILD_DIR/hass/FakeCertificate.pem
  #- touch $TRAVIS_BUILD_DIR/hass/FakeKey.pem
  #- mv $TRAVIS_BUILD_DIR/.travis_dummy/dummy_secrets.yaml hass/secrets.yaml
  #- mv $TRAVIS_BUILD_DIR/.travis_dummy/dummy_service_account.json hass/service_account.json
  #- docker pull homeassistant/home-assistant:stable
  
#script:
  #- docker run -v $TRAVIS_BUILD_DIR/hass:/config homeassistant/home-assistant:stable python -m homeassistant --config /config --script check_config --info all
