language: python

services:
  - docker

before_install:
  - touch hass/certs/FakeKey.pem
  - mv .dummy_secrets.yaml hass/secrets.yaml
  - docker-compose --version
  - docker-compose pull
  - docker-compose build
  - docker ps
  
script:
  - docker-compose up --build homeassistant-check-config