language: python

services:
  - docker

before_install:
  - mkdir hass/certs
  - touch hass/certs/FakeKey.pem
  - mv .dummy_secrets.yaml hass/secrets.yaml
  - docker-compose --version
  - docker-compose -f docker-compose.yaml -f docker-compose.ci.yaml pull
  - docker ps
  
script:
  - docker-compose -f docker-compose.yaml -f docker-compose.ci.yaml up --build homeassistant-check-config