# TODO - Move everything that was configured through UI to yaml.
homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: !secret home_unit_system
  time_zone: !secret home_timezone
  customize: !include customize.yaml

frontend:

system_health:

# Enables configuration UI
config:

http:
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key

recorder:
  purge_keep_days: 5
  exclude:
    domains:
      - automation
      - media_player
      - zwave

history:
  exclude:
    domains:
      - automation
      - media_player
      - zwave
    entities:
      - sensor.time
      - sensor.fred_last_milk_elapsed_time

logbook:
  exclude:
    domains:
      - automation
      - media_player
      - zwave
    entities:
      - sensor.time
      - sensor.fred_last_milk_elapsed_time

device_tracker:
  - platform: google_maps
    username: !secret tracker_account
    max_gps_accuracy: 100
  - platform: ping
    hosts:
      yan: !secret yan_phone_ip
      cath: !secret cath_phone_ip

map:

sun:

mqtt:
  broker: 127.0.0.1
  port: 1883
  username: !secret mqtt_username
  password: !secret mqtt_password

# TODO - move these to different files
sensor:
  - platform: time_date
    display_options:
      - 'time'
  - platform: rest
    resource: https://api.ipify.org/?format=json
    name: External IP
    value_template: '{{ value_json.ip }}'
    scan_interval: 3600
  - platform: yr
  - platform: huesensor
  - platform: waze_travel_time
    name: yantohome
    origin: person.yan
    destination: zone.home
    region: !secret home_region
  - platform: waze_travel_time
    name: cathtohome
    origin: person.cath
    destination: zone.home
    region: !secret home_region
  - platform: template
    sensors:
      frederique_ceiling_light_brightness:
        value_template: >-
          {% if is_state('light.frederique_main_light', 'on') %}
            {{ states.light.frederique_main_light.attributes.brightness }}
          {% else %}
            0
          {% endif %}
      fred_daily_milk_consumption:
        value_template: "{{ states('input_number.fred_daily_milk_consumption') | float }}"
      fred_last_milk_elapsed_time:
        friendly_name: "Depuis le dernier lait"
        value_template: '{{ (as_timestamp(now()) - states.input_datetime.fred_last_milk.attributes.timestamp ) | timestamp_custom("%Hh%M")}}'
        entity_id: input_datetime.fred_last_milk,sensor.time
      harmony_activity:
        value_template: '{{ states.remote.yharmony.attributes.current_activity }}'
        entity_id: remote.yharmony

zwave:
  usb_path: !secret zwave_usb_path
  polling_interval: 0
  network_key: !secret zwave_network_key

logger:
  default: info

remote:
  - platform: harmony
    name: YHarmony
    host: !secret harmony_ip

nissan_leaf:
  username: !secret nissan_username
  password: !secret nissan_password
  region: !secret nissan_region
  update_interval:
    days: 365

# TODO - move this to another file
google_assistant:
  project_id: !secret project_id
  service_account: !include service_account.json
  report_state: true
  expose_by_default: false
  entity_config:
    switch.light_front:
      expose: true
      name: Extérieur
      aliases:
        - Devant
        - Avant
    light.bathroom_ceiling_light:
      expose: true
      name: Salle de bain
      aliases:
        - Plafond de la salle de bain
    light.bathroom_mirror_light:
      expose: true
      name: Miroir de la salle de bain
    switch.master_bathroom_fan:
      expose: true
      name: Fan de la salle de bain
    light.kitchen_main_light:
      expose: true
      name: Cuisine
    light.living_room_main_light:
      expose: true
      name: Salon
    switch.christmas_tree_switch:
      expose: true
      name: Sapin
    light.upper_stairs_light:
      expose: true
      name: Escalier
    light.ground_floor_hallway_light:
      expose: true
      name: corridor

tts:
  - platform: google_translate
    base_url: !secret base_url_tts

notify:
  - name: yan
    platform: hangouts
    default_conversations:
      - id: !secret hangout_yan_id
  - name: cath
    platform: hangouts
    default_conversations:
      - id: !secret hangout_cath_id
  - name: all_people
    platform: group
    services:
      - service: yan
      - service: cath

light:
  - platform: hyperion
    host: !secret hyperion_ip_address
    port: !secret hyperion_port

hyperion_priority:
  host: !secret hyperion_ip_address
  port: !secret hyperion_port

zone: !include zone.yaml
alarm_control_panel: !include alarm_control_panel.yaml
switch: !include_dir_merge_list switch
binary_sensor: !include_dir_merge_list binary_sensor
group: !include groups.yaml
automation: !include_dir_merge_list automation
script: !include scripts.yaml
input_boolean: !include input_boolean.yaml
input_datetime: !include input_datetime.yaml
input_number: !include input_number.yaml
