version: '3'
services:
  # The purpose of this service is to bootstrap everything
  # and handle github webhook to update and restart everything
  # when master is updated and pass validations.
  supervisor:
    container_name: supervisor
    build: Supervisor
    volumes:
      - .:/Source
      - /var/run/docker.sock:/var/run/docker.sock
    image: supervisor:latest
    expose:
      - 3000
    restart: always
    depends_on:
      - webhookproxy

  # The purpose of this service is to receive github webhook events from the smee.io service
  # and to forward them to the supervisor service.
  webhookproxy:
    container_name: webhookproxy
    build: WebhookProxy
    image: webhookproxy:latest
    restart: always

  homeassistant:
    container_name: hass
    #image: homeassistant/home-assistant:0.113.2    #Specific Version
    image: homeassistant/home-assistant:stable
    volumes:
      - ./hass:/config
    devices:
      - /dev/zwave:/dev/zwave
    restart: always
    network_mode: host
    depends_on:
      - mqtt
      - alarm

  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto:latest
    restart: always
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config

  alarm:
    container_name: alarm
    build: alarm/
    image: alarm:latest
    restart: always
    depends_on:
      - mqtt
