---
version: '3'
services:
  homeassistant:
    container_name: hass
    # image: homeassistant/home-assistant:0.113.2    #Specific Version
    image: homeassistant/home-assistant:stable
    volumes:
      - ${BASE_PATH}/hass:/config
    restart: always
    network_mode: host
    depends_on:
      - mqtt
      - alarm
      - database
      - leaf
      - zwavejs2mqtt

  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto:latest
    restart: always
    ports:
      - "1883:1883"
    volumes:
      - ${BASE_PATH}/mosquitto/config:/mosquitto/config

  leaf:
    container_name: leaf2mqtt
    image: yp87/leaf2mqtt:latest
    restart: always
    environment:
      - LEAF_USERNAME=${LEAF_USERNAME}
      - LEAF_PASSWORD=${LEAF_PASSWORD}
      - MQTT_HOST=mqtt
      - MQTT_USERNAME=${MQTT_USERNAME}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
      - LEAF_TYPE=${LEAF_TYPE}
      - UPDATE_INTERVAL_MINUTES=1440
      - CHARGING_UPDATE_INTERVAL_MINUTES=30
      - COMMAND_ATTEMPTS=7
      - LOG_LEVEL=FINER
    depends_on:
      - mqtt

  alarm:
    container_name: alarm
    build: alarm/
    image: alarm:latest
    restart: always
    depends_on:
      - mqtt

  teslamate:
    container_name: teslamate
    image: teslamate/teslamate:latest
    restart: always
    environment:
      - DATABASE_USER=${AUTOMATION_USERNAME}
      - DATABASE_PASS=${AUTOMATION_PASSWORD}
      - DATABASE_NAME=${TESLAMATE_DATABASE}
      - DATABASE_HOST=database
      - MQTT_HOST=mqtt
      - MQTT_USERNAME=${MQTT_USERNAME}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
    ports:
      - "4000:4000"
    cap_drop:
      - all
    depends_on:
      - mqtt
      - database

  database:
    container_name: postgres
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=${AUTOMATION_USERNAME}
      - POSTGRES_PASSWORD=${AUTOMATION_PASSWORD}
      - "POSTGRES_MULTIPLE_DATABASES=${TESLAMATE_DATABASE},\
         ${HOMEASSISTANT_RECORDER_DATABASE}"
    volumes:
      - ${BASE_PATH}/volumes/automation-db:/var/lib/postgresql/data
      - "${BASE_PATH}/volumes/docker-postgresql-multiple-databases:\
         /docker-entrypoint-initdb.d"
    ports:
      - "5432:5432"

  teslamate_grafana:
    container_name: teslamate_grafana
    image: teslamate/grafana:latest
    restart: always
    environment:
      - DATABASE_USER=${AUTOMATION_USERNAME}
      - DATABASE_PASS=${AUTOMATION_PASSWORD}
      - DATABASE_NAME=${TESLAMATE_DATABASE}
      - DATABASE_HOST=database
    ports:
      - "3000:3000"
    volumes:
      - teslamate-grafana-data:/var/lib/grafana
    depends_on:
      - database

  zwavejs2mqtt:
    container_name: zwavejs2mqtt
    image: zwavejs/zwavejs2mqtt:latest
    restart: always
    tty: true
    stop_signal: SIGINT
    environment:
      - SESSION_SECRET=${ZWAVE_SESSION_SECRET}
    devices:
      - '/dev/zwave:/dev/zwave'
    volumes:
      - zwave-config:/usr/src/app/store
    ports:
      # port for web interface
      - '8091:8091'
      # port for Z-Wave JS websocket server
      - '3001:3000'

volumes:
  teslamate-grafana-data:
  zwave-config:
