version: '3'
services:
  homeassistant:
    container_name: hass
    #image: homeassistant/home-assistant:0.113.2    #Specific Version
    image: homeassistant/home-assistant:stable
    volumes:
      - /home/hass/hass:/config
    devices:
      - /dev/zwave:/dev/zwave
    restart: always
    network_mode: host
