version: '3'
services:
  homeassistant:
    container_name: hass
    #image: homeassistant/home-assistant:0.113.2    #Specific Version
    image: homeassistant/home-assistant:stable
    volumes:
      - .:/config
    devices:
      - /dev/zwave:/dev/zwave
    restart: always
    network_mode: host
    depends_on:
      mqtt:
        condition: service_started

  mqtt:
    image: eclipse-mosquitto:latest
    container_name: "mqtt"
    restart: always
    network_mode: host
    ports:
      - 1883:1883
    volumes:
      - ../mosquitto/config:/mosquitto/config
