version: '3'
services:
  # The purpose of this service is to bootstrap everything
  # and handle github webhook (through smoo.io) to update and restart everything
  # when master is updated and pass validations.
  webhookproxy:
    container_name: webhookproxy
    build: WebhookProxy
    image: webhookproxy:latest
    restart: always

  homeassistant:
    container_name: hass
    #image: homeassistant/home-assistant:0.113.2    #Specific Version
    image: homeassistant/home-assistant:stable
    volumes:
      - ./hass:/config
    devices:
      - /dev/zwave:/dev/zwave
    restart: always
    network_mode: host
    depends_on:
      - mqtt
      - alarm

  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto:latest
    restart: always
    network_mode: host
    ports:
      - 1883:1883
    volumes:
      - ./mosquitto/config:/mosquitto/config

  alarm:
    container_name: alarm
    build: alarm/
    image: alarm:latest
    restart: always
    network_mode: host
