version: '2'
services:
  homeassistant:
    extends:
      file: docker-compose.base.yaml
      service: homeassistant-base
    devices:
      - /dev/zwave:/dev/zwave
    restart: always
    network_mode: host
    depends_on:
      - mqtt

  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto:latest
    restart: always
    network_mode: host
    ports:
      - 1883:1883
    volumes:
      - ./mosquitto/config:/mosquitto/config
