---
version: '3'
services:
  # The purpose of this service is to bootstrap everything
  # and handle github webhook to update and restart everything
  # when master is updated and pass validations.
  supervisor:
    container_name: supervisor
    build: Supervisor
    volumes:
      - .:/Source
      - /var/run/docker.sock:/var/run/docker.sock
    image: supervisor:latest
    expose:
      - 3000
    environment:
      - BASE_PATH=$PWD
    restart: always
    depends_on:
      - webhookproxy

  # The purpose of this service is to
  # receive github webhook events from the smee.io service
  # and to forward them to the supervisor service.
  webhookproxy:
    container_name: webhookproxy
    build: WebhookProxy
    image: webhookproxy:latest
    restart: always

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
    environment:
    volumes:
      - pihole:/etc/pihole
      - pihole-dnsmasq:/etc/dnsmasq.d
    restart: unless-stopped

volumes:
  pihole:
  pihole-dnsmasq:
