---
version: '3'
services:
  homeassistant:
    container_name: hass
    # image: homeassistant/home-assistant:0.113.2    #Specific Version
    image: homeassistant/home-assistant:stable
    environment:
      - BASE_PATH
    volumes:
      - ${BASE_PATH}/hass:/config
    devices:
      - /dev/zwave:/dev/zwave
    restart: always
    network_mode: host
    depends_on:
      - mqtt
      - alarm

  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto:latest
    restart: always
    ports:
      - "1883:1883"
    environment:
      - BASE_PATH
    volumes:
      - ${BASE_PATH}/mosquitto/config:/mosquitto/config

  alarm:
    container_name: alarm
    build: alarm/
    image: alarm:latest
    restart: always
    depends_on:
      - mqtt

  teslamate:
    container_name: teslamate
    image: teslamate/teslamate:latest
    restart: always
    environment:
      - DATABASE_USER=${automation_username}
      - DATABASE_PASS=${automation_password}
      - DATABASE_NAME=${teslamate_database}
      - DATABASE_HOST=database
      - MQTT_HOST=mqtt
    ports:
      - "4000:4000"
    cap_drop:
      - all
    depends_on:
      - mqtt
      - database

  database:
    container_name: postgres
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=${automation_username}
      - POSTGRES_PASSWORD=${automation_password}
      - POSTGRES_DB=${teslamate_database}
    volumes:
      - ${BASE_PATH}/volumes/automation-db:/var/lib/postgresql/data

  teslamate_grafana:
    container_name: teslamate_grafana
    image: teslamate/grafana:latest
    restart: always
    environment:
      - DATABASE_USER=${automation_username}
      - DATABASE_PASS=${automation_password}
      - DATABASE_NAME=${teslamate_database}
      - DATABASE_HOST=database
    ports:
      - "3000:3000"
    volumes:
      - teslamate-grafana-data:/var/lib/grafana
    depends_on:
      - database

volumes:
  teslamate-grafana-data:
