---
homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: !secret home_unit_system
  time_zone: !secret home_timezone
  customize: !include customize.yaml

frontend:

system_health:

# Enables configuration UI
config:

http:
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key

recorder:
  db_url: !secret recorder_database_url
  purge_keep_days: 367
  exclude:
    domains:
      - automation
      - media_player
      - zwave
    entities:
      - light.table_de_chevet_de_yan
      - light.table_de_chevet_de_cath

history:

logbook:

device_tracker:
  - platform: google_maps
    username: !secret tracker_account
    max_gps_accuracy: 100
  - platform: ping
    hosts:
      yan: !secret yan_phone_ip
      cath: !secret cath_phone_ip

map:

sun:

media_player:
  - platform: androidtv
    name: Living room TV
    host: 192.168.1.37
    screencap: false
    get_sources: false

mqtt:
  broker: 127.0.0.1
  port: 1883
  username: !secret mqtt_username
  password: !secret mqtt_password

zwave:
  usb_path: !secret zwave_usb_path
  polling_interval: 0
  network_key: !secret zwave_network_key

logger:
  default: info

# TODO - move this to another file
google_assistant:
  project_id: !secret project_id
  service_account: !include service_account.json
  report_state: true
  expose_by_default: false
  entity_config:
    switch.light_front:
      expose: true
      name: Extérieur
      aliases:
        - Devant
        - Avant
    light.bathroom_ceiling_light:
      expose: true
      name: Salle de bain
      aliases:
        - Plafond de la salle de bain
    light.bathroom_mirror_light:
      expose: true
      name: Miroir de la salle de bain
    switch.master_bathroom_fan:
      expose: true
      name: Fan de la salle de bain
      aliases:
        - Fan
    light.kitchen_main_light:
      expose: true
      name: Cuisine
    light.living_room_main_light:
      expose: true
      name: Salon
  # light.twinkly_a80df9:
    # expose: true
    # name: Sapin
    light.upper_stairs_light:
      expose: true
      name: Escalier
    light.ground_floor_hallway_light:
      expose: true
      name: corridor
    script.start_the_leaf:
      expose: true
      name: La Leaf
    script.charge_the_leaf:
      expose: true
      name: Charge la Leaf
    switch.bibicar_climate:
      expose: true
      name: La Tesla

tts:
  - platform: google_translate
    base_url: !secret base_url_tts

notify:
  - name: yan
    platform: hangouts
    default_conversations:
      - id: !secret hangout_yan_id
  - name: cath
    platform: hangouts
    default_conversations:
      - id: !secret hangout_cath_id
  - name: all_people
    platform: group
    services:
      - service: yan
      - service: cath

light:
  - platform: hyperion_classic
    host: !secret hyperion_ip_address
    port: !secret hyperion_port

hyperion_priority:
  host: !secret hyperion_ip_address
  port: !secret hyperion_port

rest_command:
  update_dns_ip:
    url: !secret dns_ip_update_url

zone: !include zone.yaml
alarm_control_panel: !include alarm_control_panel.yaml
switch: !include_dir_merge_list switch
binary_sensor: !include_dir_merge_list binary_sensor
sensor: !include_dir_merge_list sensor
group: !include groups.yaml
automation: !include_dir_merge_list automation
script: !include scripts.yaml
input_boolean: !include input_boolean.yaml
input_text: !include input_text.yaml
input_number: !include input_number.yaml
input_select: !include input_select.yaml
