---
homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: !secret home_unit_system
  customize: !include customize.yaml
  time_zone: !secret home_timezone
  external_url: !secret external_url
  currency: !secret currency
  country: !secret country

frontend:

system_health:

# Enables configuration UI
config:

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1

recorder:
  db_url: !secret recorder_database_url
  purge_keep_days: 1825
  exclude:
    domains:
      - automation
      - media_player
    entities:
      - light.table_de_chevet_de_yan
      - light.table_de_chevet_de_cath

history:

schedule:

logbook:

device_tracker:
  - platform: google_maps
    username: !secret tracker_account
    max_gps_accuracy: 100

sun:

logger:
  default: info

backup:

media_source:

# TODO - move this to another file
google_assistant:
  project_id: !secret project_id
  service_account: !include service_account.json
  report_state: true
  expose_by_default: false
  entity_config:
    switch.light_front:
      expose: true
      name: Extérieur
      aliases:
        - Devant
        - Avant
    light.bathroom_ceiling_light:
      expose: true
      name: Salle de bain
      aliases:
        - Plafond de la salle de bain
    light.bathroom_mirror_light:
      expose: true
      name: Miroir de la salle de bain
    switch.master_bathroom_fan:
      expose: true
      name: Fan de la salle de bain
      aliases:
        - Fan
    light.kitchen_main_light:
      expose: true
      name: Cuisine
    light.living_room_main_light:
      expose: true
      name: Salon
    light.twinkly_a80df9:
      expose: true
      name: Sapin
    light.upper_stairs_light:
      expose: true
      name: Escalier
    light.ground_floor_hallway_light:
      expose: true
      name: corridor
    cover.kitchen_window_blind:
      expose: true
      name: Fenêtre de la cuisine
    cover.patio_door_blind:
      expose: true
      name: Fenêtre du patio
    cover.living_room_window_blind:
      expose: true
      name: Fenêtre du salon
    cover.office_window_blind:
      expose: true
      name: Fenêtre du bureau
    climate.main_floor:
      expose: true
      name: Thermostat

tts:
  - platform: google_translate

notify:
  - name: all_people
    platform: group
    services:
      - service: yan
      - service: cath
  - name: yan
    platform: group
    services:
      - service: pushover
        data:
          target: pixel7
  - platform: joaoapps_join
    api_key: !secret join_phone_api_key_cath
    device_id: !secret join_phone_device_cath
    name: cath

shell_command:
  set_garage_camera_time: !secret camera_garage_set_time_template
  set_front_window_camera_time: !secret camera_front_window_set_time_template
  set_rear_window_camera_time: !secret camera_rear_window_set_time_template
  set_parking_camera_time: !secret camera_parking_set_time_template

stream:

hyperion_priority:
  host: !secret hyperion_ip_address
  port: !secret hyperion_port

gemini_api:
  api_key: !secret gemini_api_key

rest_command:
  update_dns_ip:
    url: !secret dns_ip_update_url
  garage_camera_output:
    url: !secret camera_garage_output_url
    username: !secret camera_garage_username
    password: !secret camera_garage_password

conversation:
#assist_pipeline:

joaoapps_join:
  - name: android_server
    device_id: !secret join_android_server_device
    api_key: !secret join_android_server_api_key
  - name: phone
    device_id: !secret join_phone_device
    api_key: !secret join_phone_api_key

automation: !include_dir_merge_list automation
group: !include groups.yaml
input_boolean: !include input_boolean.yaml
input_button: !include input_button.yaml
script: !include_dir_merge_named script
sensor: !include_dir_merge_list sensor
switch: !include_dir_merge_list switch
zone: !include zone.yaml
template: !include_dir_merge_list template
command_line: !include_dir_merge_list command_line

mqtt:
  sensor: !include_dir_merge_list mqtt/sensor
  switch: !include_dir_merge_list mqtt/switch
  binary_sensor: !include_dir_merge_list mqtt/binary_sensor
  alarm_control_panel: !include_dir_merge_list mqtt/alarm_control_panel
