- platform: mqtt
  name: tesla_charge_port_door_open
  state_topic: "teslamate/cars/1/charge_port_door_open"
  device_class: door

- platform: mqtt
  name: tesla_healthy
  state_topic: "teslamate/cars/1/healthy"
  device_class: connectivity

- platform: mqtt
  name: tesla_locked
  state_topic: "teslamate/cars/1/locked"
  device_class: lock

- platform: mqtt
  name: tesla_plugged_in
  state_topic: "teslamate/cars/1/plugged_in"
  device_class: plug

- platform: mqtt
  name: tesla_windows_open
  state_topic: "teslamate/cars/1/windows_open"
  device_class: window

- platform: template
  sensors:
    tesla_park_brake:
      friendly_name: Park Brake
      value_template: >-
        {% if is_state('sensor.tesla_shift_state', 'P') %}
          true
        {% else %}
          false
        {% endif %}
