---
- platform: mqtt
  name: tesla_charge_port_door_open
  state_topic: "teslamate/cars/1/charge_port_door_open"
  payload_on: "true"
  payload_off: "false"
  device_class: door

- platform: mqtt
  name: tesla_healthy
  state_topic: "teslamate/cars/1/healthy"
  payload_on: "true"
  payload_off: "false"
  device_class: connectivity

- platform: mqtt
  name: tesla_locked
  state_topic: "teslamate/cars/1/locked"
  payload_on: "true"
  payload_off: "false"
  device_class: lock

- platform: mqtt
  name: tesla_plugged_in
  state_topic: "teslamate/cars/1/plugged_in"
  payload_on: "true"
  payload_off: "false"
  device_class: plug

- platform: mqtt
  name: tesla_windows_open
  state_topic: "teslamate/cars/1/windows_open"
  payload_on: "true"
  payload_off: "false"
  device_class: window

- platform: mqtt
  name: tesla_trunk_open
  state_topic: "teslamate/cars/1/trunk_open"
  payload_on: "true"
  payload_off: "false"
  device_class: door

- platform: mqtt
  name: tesla_frunk_open
  state_topic: "teslamate/cars/1/frunk_open"
  payload_on: "true"
  payload_off: "false"
  device_class: door

- platform: mqtt
  name: tesla_doors_open
  state_topic: "teslamate/cars/1/doors_open"
  payload_on: "true"
  payload_off: "false"
  device_class: door

- platform: template
  sensors:
    tesla_park_brake:
      friendly_name: Park Brake
      value_template: >-
        {% if is_state('sensor.tesla_shift_state', 'P') %}
          on
        {% else %}
          off
        {% endif %}
