---
- alias: Initialize bibicar update to false
  trigger:
    platform: homeassistant
    event: start
  action:
    service: switch.turn_off
    entity_id: switch.bibicar_update_switch

- alias: Notify when something is wrong when parking
  trigger:
    - platform: state
      entity_id: sensor.tesla_state
      to: "online"
      for: "00:05:00"
    - platform: state
      entity_id: sensor.tesla_state
      to: "suspended"
      for: "00:05:00"
  condition:
    - condition: not
      conditions:
        - condition: state
          entity_id:
            - binary_sensor.tesla_windows_open
            - binary_sensor.tesla_trunk_open
            - binary_sensor.tesla_frunk_open
            - binary_sensor.tesla_doors_open
          state: "off"
        - condition: state
          entity_id: binary_sensor.tesla_locked
          state: "on"
  action:
    - service: script.notify_and_speak
      data:
        variables:
          message: >-
            La Tesla est arrêtée, mais
            {%- set stringMap = [
              ("tesla_windows_open", "on", "une fenêtre est ouverte"),
              ("tesla_trunk_open", "on", "la valise arrière est ouverte"),
              ("tesla_frunk_open", "on", "la valise avant est ouverte"),
              ("tesla_doors_open", "on", "une porte est ouverte"),
              ("tesla_locked", "off", "les portes sont débarrées"),
            ] -%}
            {%- for entity_id, problemState, string in stringMap
                if is_state("binary_sensor."+entity_id, problemState) %}
              {%- if loop.last and not loop.first %} et {% elif loop.first -%}
              {{ " " }}{% else %}, {% endif -%}
              {{string}}
            {%- endfor %}.

- alias: Notify when something is wrong when parked
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.tesla_windows_open
        - binary_sensor.tesla_trunk_open
        - binary_sensor.tesla_frunk_open
        - binary_sensor.tesla_doors_open
      to: "on"
      for: "00:05:00"
    - platform: state
      entity_id: binary_sensor.tesla_locked
      to: "off"
      for: "00:05:00"
  condition:
    condition: not
    conditions:
      - condition: state
        entity_id: sensor.tesla_state
        state: "driving"
  action:
    - service: script.notify_and_speak
      data:
        variables:
          message: >-
            {%- set stringMap = ({
              "on": "ouverte",
              "off": "débarrées",
              "tesla_windows_open": "une fenêtre est",
              "tesla_trunk_open": "la valise arrière est",
              "tesla_frunk_open": "la valise avant est",
              "tesla_doors_open": "une porte est",
              "tesla_locked": "les portières sont",
            }) -%}
            La Tesla est arrêtée, mais{{ " " }}
            {{- stringMap[trigger.to_state.object_id] }}{{ " " }}
            {{- stringMap[trigger.to_state.state] }}.
