---
- alias: Initialize bibicar update to false
  trigger:
    platform: homeassistant
    event: start
  action:
    service: switch.turn_off
    entity_id: switch.bibicar_update_switch

- alias: Notify when something is wrong when parking
  trigger:
    - platform: state
      entity_id: sensor.tesla_state
      to: "online"
      for: "00:05:00"
    - platform: state
      entity_id: sensor.tesla_state
      to: "suspended"
      for: "00:05:00"
    - platform: state
      entity_id: sensor.yantotesla
    - platform: state
      entity_id: sensor.cathtotesla
  condition:
    - condition: not
      conditions:
        - condition: state
          entity_id:
            - binary_sensor.tesla_windows
            - binary_sensor.tesla_trunk
            - binary_sensor.tesla_frunk
            - binary_sensor.tesla_doors
            - binary_sensor.tesla_lock
          state: "off"
    - "{{ state_attr('sensor.yantotesla', 'distance')|float > 0.100 }}"
    - "{{ state_attr('sensor.cathtotesla', 'distance')|float > 0.100 }}"
  action:
    - service: script.notify_and_speak
      data:
        message: >-
          La Tesla est arrêtée, mais
          {%- set stringMap = [
            ("tesla_windows", "une fenêtre est ouverte"),
            ("tesla_trunk", "la valise arrière est ouverte"),
            ("tesla_frunk", "la valise avant est ouverte"),
            ("tesla_doors", "une porte est ouverte"),
            ("tesla_lock", "les portes sont débarrées"),
          ] -%}
          {%- for entity_id, string in stringMap
              if is_state("binary_sensor."+entity_id, "on") %}
            {%- if loop.last and not loop.first %} et {% elif loop.first -%}
            {{ " " }}{% else %}, {% endif -%}
            {{string}}
          {%- endfor %}.

- alias: Notify when something is wrong when parked
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.tesla_windows
        - binary_sensor.tesla_trunk
        - binary_sensor.tesla_frunk
        - binary_sensor.tesla_doors
        - binary_sensor.tesla_lock
      to: "on"
      for: "00:05:00"
  condition:
    - condition: not
      conditions:
        - condition: state
          entity_id: sensor.tesla_state
          state: "driving"
    - "{{ state_attr('sensor.yantotesla', 'distance')|float > 0.100 }}"
    - "{{ state_attr('sensor.cathtotesla', 'distance')|float > 0.100 }}"
  action:
    - service: script.notify_and_speak
      data:
        message: >-
          {%- set stringMap = ({
            "tesla_windows": "une fenêtre est ouverte",
            "tesla_trunk": "la valise arrière est ouverte",
            "tesla_frunk": "la valise avant est ouverte",
            "tesla_doors": "une porte est ouverte",
            "tesla_lock": "les portières sont débarrées",
          }) -%}
          La Tesla est arrêtée, mais{{ " " }}
          {{- stringMap[trigger.to_state.object_id] }}.

- alias: update tesla gps coordinates
  trigger:
    platform: state
    entity_id:
      - sensor.tesla_latitude
      - sensor.tesla_longitude
  action:
    - service: device_tracker.see
      data_template:
        dev_id: tesla
        gps:
          - "{{ states('sensor.tesla_latitude') }}"
          - "{{ states('sensor.tesla_longitude') }}"
