---
- alias: Initialize bibicar update to false
  trigger:
    platform: homeassistant
    event: start
  action:
    service: switch.turn_off
    entity_id: switch.bibicar_update_switch

- alias: Notify when something is wrong when parking
  trigger:
    - platform: state
      entity_id: sensor.tesla_state
      to: "online"
      for: "00:05:00"
    - platform: state
      entity_id: sensor.tesla_state
      to: "suspended"
      for: "00:05:00"
  condition:
    - condition: not
      conditions:
        - condition: state
          entity_id:
            - binary_sensor.tesla_windows
            - binary_sensor.tesla_trunk
            - binary_sensor.tesla_frunk
            - binary_sensor.tesla_doors
            - binary_sensor.tesla_lock
          state: "off"
  action:
    - service: script.notify_and_speak
      data:
        message: >-
          La Tesla est arrêtée, mais
          {%- set stringMap = [
            ("tesla_windows", "une fenêtre est ouverte"),
            ("tesla_trunk", "la valise arrière est ouverte"),
            ("tesla_frunk", "la valise avant est ouverte"),
            ("tesla_doors", "une porte est ouverte"),
            ("tesla_lock", "les portes sont débarrées"),
          ] -%}
          {%- for entity_id, string in stringMap
              if is_state("binary_sensor."+entity_id, "on") %}
            {%- if loop.last and not loop.first %} et {% elif loop.first -%}
            {{ " " }}{% else %}, {% endif -%}
            {{string}}
          {%- endfor %}.

- alias: Notify when something is wrong when parked
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.tesla_windows
        - binary_sensor.tesla_trunk
        - binary_sensor.tesla_frunk
        - binary_sensor.tesla_doors
        - binary_sensor.tesla_lock
      to: "on"
      for: "00:05:00"
  condition:
    condition: not
    conditions:
      - condition: state
        entity_id: sensor.tesla_state
        state: "driving"
  action:
    - service: script.notify_and_speak
      data:
        message: >-
          {%- set stringMap = ({
            "tesla_windows": "une fenêtre est ouverte",
            "tesla_trunk": "la valise arrière est ouverte",
            "tesla_frunk": "la valise avant est ouverte",
            "tesla_doors": "une porte est ouverte",
            "tesla_lock": "les portières sont débarrées",
          }) -%}
          La Tesla est arrêtée, mais{{ " " }}
          {{- stringMap[trigger.to_state.object_id] }}.
