---
- alias: Notify when something is opened while exiting the car
  trigger:
    - platform: state
      entity_id:
        - input_boolean.cath_in_tesla
        - input_boolean.yan_in_tesla
      to: "off"
      for: "00:03:00"
  condition:
    - condition: not
      conditions:
        - condition: state
          entity_id:
            - binary_sensor.tesla_windows
            - binary_sensor.tesla_trunk
            - binary_sensor.tesla_frunk
            - binary_sensor.tesla_doors
            - binary_sensor.tesla_lock
          state: "off"
  action:
    - service: script.notify_and_speak
      data:
        message: >-
          La Tesla est arrêtée, mais
          {%- set stringMap = [
            ("tesla_windows", "une fenêtre est ouverte"),
            ("tesla_trunk", "la valise arrière est ouverte"),
            ("tesla_frunk", "la valise avant est ouverte"),
            ("tesla_doors", "une porte est ouverte"),
            ("tesla_lock", "les portes sont débarrées"),
          ] -%}
          {%- for entity_id, string in stringMap
              if is_state("binary_sensor."+entity_id, "on") %}
            {%- if loop.last and not loop.first %} et {% elif loop.first -%}
            {{ " " }}{% else %}, {% endif -%}
            {{string}}
          {%- endfor %}.

- alias: Notify when something is opened and no one is in the car
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.tesla_windows
        - binary_sensor.tesla_trunk
        - binary_sensor.tesla_frunk
        - binary_sensor.tesla_doors
        - binary_sensor.tesla_lock
      to: "on"
      for: "00:05:00"
  condition:
    - condition: state
      entity_id: input_boolean.cath_in_tesla
      state: "off"
    - condition: state
      entity_id: input_boolean.yan_in_tesla
      state: "off"
  mode: single
  max_exceeded: silent
  action:
    - service: script.notify_and_speak
      data:
        message: >-
          {%- set stringMap = ({
            "tesla_windows": "une fenêtre est ouverte",
            "tesla_trunk": "la valise arrière est ouverte",
            "tesla_frunk": "la valise avant est ouverte",
            "tesla_doors": "une porte est ouverte",
            "tesla_lock": "les portières sont débarrées",
          }) -%}
          La Tesla est arrêtée, mais{{ " " }}
          {{- stringMap[trigger.to_state.object_id] }}.

- alias: Tesla - Normal Max charge
  id: Tesla_Normal_Max_charge
  trigger:
    - platform: state
      entity_id: device_tracker.tesla_location
      to: "home"
    - platform: state
      entity_id: binary_sensor.tesla_climate
      to: "off"
  action:
    - service: tesla_custom.api
      data:
        command: CHANGE_CHARGE_LIMIT
        parameters:
          path_vars:
            vehicle_id: !secret tesla_vehicle_id
          wake_if_asleep: false
          percent: 80

- alias: Tesla - High Max charge
  id: Tesla_High_Max_charge
  trigger:
    - platform: state
      entity_id: binary_sensor.tesla_climate
      to: "on"
  action:
    - service: tesla_custom.api
      data:
        command: CHANGE_CHARGE_LIMIT
        parameters:
          path_vars:
            vehicle_id: !secret tesla_vehicle_id
          wake_if_asleep: false
          percent: 90

- alias: Tesla - Location
  id: Tesla_Location
  trigger:
    - platform: mqtt
      topic: teslamate/cars/1/latitude
    - platform: mqtt
      topic: teslamate/cars/1/longitude
  mode: single
  max_exceeded: silent
  action:
    - delay: "00:00:10"
    - service: device_tracker.see
      data_template:
        dev_id: tesla_location
        gps:
          - "{{ states.sensor.tesla_latitude.state }}"
          - "{{ states.sensor.tesla_longitude.state }}"
