---
- platform: mqtt
  unique_id: leaf_battery_level
  name: "Batterie Leaf"
  state_topic: "leaf/battery/percentage"
  unit_of_measurement: "%"
  device_class: battery

- platform: mqtt
  name: leaf_battery_last_updated
  state_topic: "leaf/battery/lastUpdatedDateTimeUtc"
  device_class: timestamp
