---
- platform: mqtt
  name: leaf_battery_level
  state_topic: "leaf/battery/percentage"
  unit_of_measurement: "%"
  device_class: battery

- platform: mqtt
  name: leaf_battery_last_updated
  state_topic: "leaf/battery/lastUpdatedDateTimeUtc"
  device_class: timestamp

- platform: mqtt
  name: leaf_battery_last_received
  state_topic: "leaf/battery/lastReceivedDateTimeUtc"
  device_class: timestamp

- platform: template
  sensors:
    leaf_charge_per_hour:
      value_template: "{{ states('input_number.leaf_charge_per_hour') }}"
    leaf_next_departure:
      friendly_name: Heure de départ Leaf
      value_template: "{{ states('input_datetime.leaf_next_departure') }}"
    leaf_start_charging:
      friendly_name: Heure de charge Leaf
      value_template: "{{ states('input_datetime.leaf_start_charging') }}"
    leaf_start_climate:
      friendly_name: Heure de régulation de température Leaf
      value_template: "{{ states('input_datetime.leaf_start_climate') }}"
