---
- platform: template
  sensors:
    front_door_action:
      value_template: >
        {% if is_state('sensor.front_door_lock_alarm_type', '22') %}
          Manual Unlock
        {% elif is_state('sensor.front_door_lock_alarm_type', '21') %}
          Manual Lock
        {% elif is_state('sensor.front_door_lock_alarm_type', '19') %}
          Keypad Unlock
        {% elif is_state('sensor.front_door_lock_alarm_type', '18') %}
          Keypad Lock
        {% elif is_state('sensor.front_door_lock_alarm_type', '25') %}
          Wireless Unlock
        {% elif is_state('sensor.front_door_lock_alarm_type', '24') %}
          Wireless Lock
        {% elif is_state('sensor.front_door_lock_alarm_type', '9') %}
          Lock Jammed
        {% elif is_state('sensor.front_door_lock_alarm_type', '161') %}
          Tamper Alarm
        {% else %}
          Other
        {% endif %}

    leaf_charge_per_hour:
      value_template: "{{ states('input_number.leaf_charge_per_hour') }}"
