---
- alias: Open blinds in the morning
  id: open_blinds_in_the_morning
  trigger:
    - platform: sun
      event: sunrise
      offset: 00:30:00
    - platform: state
      entity_id: climate.main_floor
      attribute: preset_mode
      from: sleep
      to: Home
    - platform: time
      at: "06:30:00"
    - platform: time
      at: "07:00:00"
  condition:
    - condition: sun
      after: sunrise
      after_offset: 00:30:00
      before: sunset
      before_offset: -00:10:00
    - or:
        - condition: time
          after: "06:30:00"
          weekday:
            - mon
            - tue
            - wed
            - thu
            - fri
        - condition: time
          after: "07:00:00"
          weekday:
            - sat
            - sun
    - not:
        condition: state
        entity_id: climate.main_floor
        attribute: preset_mode
        state: sleep
  action:
    - service: cover.open_cover
      entity_id: group.all_blinds

- alias: Close blinds in the evening
  id: close_blinds_in_the_evening
  trigger:
    - platform: sun
      event: sunset
      offset: -00:10:00
    - platform: state
      entity_id: climate.main_floor
      attribute: preset_mode
      to: sleep
  action:
    - service: cover.close_cover
      data_template:
        entity_id: >
          {% if trigger.platform == 'sun' and state_attr('cover.kitchen_window_blind', 'current_position') | int == 30 %}
            {{ expand('group.all_blinds') | map(attribute='entity_id') | reject('equalto', 'cover.kitchen_window_blind') | list | join(', ') }}
          {% else %}
            group.all_blinds
          {% endif %}

- alias: CLose office blind when kid goes to sleep
  id: cLose_office_blind_when_kid_goes_to_sleep
  trigger:
    - platform: state
      entity_id: switch.baby_monitor
      to: "on"
  condition:
    - condition: time
      after: "18:00:00"
  action:
    - service: cover.close_cover
      entity_id: cover.office_window_blind

- alias: Sync office blind with sun when working
  id: sync_office_blind_with_sun_when_working
  trigger:
    - platform: time_pattern
      minutes: '/5'
    - platform: state
      entity_id: binary_sensor.laptop_wifi
      to: "on"
    - platform: state
      entity_id: binary_sensor.laptop_ethernet
      to: "on"
  condition:
    - or:
        - condition: state
          entity_id: binary_sensor.laptop_wifi
          state: "on"
        - condition: state
          entity_id: binary_sensor.laptop_ethernet
          state: "on"
    - condition: numeric_state
      entity_id: sun.sun
      value_template: "{{ state_attr('sun.sun', 'azimuth') }}"
      above: 239
    - condition: numeric_state
      entity_id: sun.sun
      value_template: "{{ state_attr('sun.sun', 'elevation') }}"
      below: 45
    - condition: time
      after: '07:00:00'
      before: '16:00:00'
      weekday:
        - mon
        - wed
        - fri
  action:
    - service: cover.set_cover_position
      data_template:
        entity_id: cover.office_window_blind
        position: >
          {% set azimuth = state_attr('sun.sun', 'azimuth') %}
          {% set position = 100 - ((azimuth - 239) * 0.5) %}
          {{ [0, position] | max }}
