---
- alias: Open blinds in the morning
  id: open_blinds_in_the_morning
  trigger:
    - platform: sun
      event: sunrise
      offset: 00:30:00
    - platform: state
      entity_id: climate.main_floor
      attribute: climate_mode
      from: Sleep
      to: Home
  condition:
    - condition: sun
      after: sunrise
      after_offset: 00:30:00
      before: sunset
      before_offset: -00:30:00
    - not:
        condition: state
        entity_id: climate.main_floor
        attribute: climate_mode
        state: Sleep
  action:
    - service: cover.open_cover
      entity_id: group.all_blinds

- alias: Close blinds in the evening
  id: close_blinds_in_the_evening
  trigger:
    - platform: sun
      event: sunset
      offset: -00:30:00
    - platform: state
      entity_id: climate.main_floor
      attribute: climate_mode
      to: Sleep
  action:
    - service: cover.open_cover
      entity_id: group.all_blinds

- alias: Sync living room blinds with TV
  id: sync living room blinds with tv
  trigger:
    - platform: state
      entity_id: remote.salon_tv
  condition:
    - condition: sun
      after: sunrise
      after_offset: 00:30:00
      before: sunset
      before_offset: -00:30:00
  action:
    - service: "cover.{{ 'close' if trigger.to_state.state == 'on' else 'open' }}_cover"
      entity_id: cover.living_room_window_blind

#- alias: Sync office blind with sun when working
#  id: sync_office_blind_with_sun_when_working
#  trigger:
#    -
