---
- alias: Notify when ender3 print is done
  id: Notify_when_ender3_print_is_done
  trigger:
    platform: state
    entity_id: sensor.octoprint_job_percentage
    to: '100'
  action:
    - service: script.notify_and_speak
      data:
        message: L'impression 3D est terminée.
