---
- alias: Google tv turns on
  id: google_tv_turns_on
  trigger:
    - platform: state
      entity_id: remote.salon_tv
      to: 'on'
  action:
    - service: select.select_option
      data:
        entity_id: select.yharmony_activities
        option: "Regarder Chromecast"

- alias: Google tv turns off
  id: google_tv_turns_off
  trigger:
    platform: state
    entity_id: remote.salon_tv
    to: 'off'
  condition:
    condition: state
    entity_id: select.yharmony_activities
    state: "Regarder Chromecast"
  action:
    - service: select.select_option
      data:
        entity_id: select.yharmony_activities
        options: "Power Off"
