---
- alias: tv notif phone ringing
  trigger:
    - platform: state
      entity_id: input_boolean.yan_phone_rings
      to: "on"
    - platform: state
      entity_id: input_boolean.cath_phone_rings
      to: "on"
  variables:
    name: >-
      {% if trigger.entity_id == "input_boolean.yan_phone_rings" %}
        Yan
      {% else %}
        Cath
      {% endif %}
  action:
    - service: notify.tv
      data:
        message: "{{ name }}'s phone is ringing"

- alias: tv notif phone notification
  trigger:
    - platform: state
      entity_id: input_boolean.yan_phone_notification
    - platform: state
      entity_id: input_boolean.cath_phone_notification
  variables:
    name: >-
      {% if trigger.entity_id == "input_boolean.yan_phone_notification" %}
        Yan
      {% else %}
        Cath
      {% endif %}
  mode: queued
  action:
    - service: notify.tv
      data:
        message: "{{ name }} received a message"
