---
- alias: tv notif phone ringing
  trigger:
    - platform: state
      entity_id: input_boolean.yan_phone_rings
      to: "on"
    - platform: state
      entity_id: input_boolean.cath_phone_rings
      to: "on"
  variables:
    name: >-
      {% if trigger.entity_id == "input_boolean.yan_phone_rings" %}
        Yan
      {% else %}
        Cath
      {% endif %}
  action:
    - service: notify.tv
      data:
        message: "{{ name }}'s phone is ringing"

- alias: tv notif phone notification
  trigger:
    - platform: state
      entity_id: input_boolean.yan_phone_notification
    - platform: state
      entity_id: input_boolean.cath_phone_notification
  variables:
    name: >-
      {% if trigger.entity_id == "input_boolean.yan_phone_notification" %}
        Yan
      {% else %}
        Cath
      {% endif %}
  mode: queued
  action:
    - service: notify.tv
      data:
        message: "{{ name }} received a message"

- alias: tv turns on
  id: tv_turns_on
  trigger:
    - platform: state
      entity_id: media_player.tv
      to: 'on'
  condition:
    condition: state
    entity_id: select.yharmony_activities
    state: "power_off"
  action:
    - service: select.select_option
      data:
        entity_id: select.yharmony_activities
        option: "Regarder Chromecast"

- alias: tv turns off
  id: tv_turns_off
  trigger:
    platform: state
    entity_id: media_player.tv
    to: 'off'
  condition:
    condition: state
    entity_id: select.yharmony_activities
    state: "Regarder Chromecast"
  action:
    - service: select.select_option
      data:
        entity_id: select.yharmony_activities
        option: "power_off"

