---
- alias: Diaper cleaning notification
  trigger:
    - platform: state
      entity_id: input_select.diaper_cleaning_state
    - platform: zone
      zone: zone.home
      entity_id: person.cath, person.yan
      event: enter
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      from: 'armed_home'
    - platform: time
      at: "12:00:00"
  condition:
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state: 'disarmed'
    - condition: or
      conditions:
        - >
          {{ trigger.platform == "state" and
             trigger.to_state.object_id == "diaper_cleaning_state" }}
        - condition: and
          conditions:
            - '{{ "Attente" in states("input_select.diaper_cleaning_state") }}'
            - >
              {{ states("input_select.diaper_cleaning_state") !=
                 "Attente du premier rinçage" }}
  action:
    - service: notify.all_people
      data:
        message: >-
          {% set state = states("input_select.diaper_cleaning_state") %}
          {{ state }} des couches.
          {%- if state == "Attente du premier rinçage" %}
          Shake - No Wet Bag - Heavy Duty - Cold - Spin High - Soil Heavy
          {% elif state == "Attente du deuxième rinçage" %}
          Shake - No Wet Bag - Heavy Duty - Cold - Spin High - Soil Heavy
          {% elif state == "Attente du premier lavage" %}
          Shake - No Wet Bag - Heavy Duty - Soap Bottom Line - Hot
          {{- " " }}- Spin High - Soil Heavy - Jet Wash
          {% elif state == "Attente du deuxième lavage" %}
          Shake - Add Wet Bag - Heavy Duty - Soap Top Line - Hot
          {{- " " }}- Spin High - Soil Heavy - Jet Wash
          {% elif state == "Attente du troisième rinçage" %}
          Shake - Normal - Warm - Spin High - Soil Normal
          {% elif state == "Attente du premier séchage" %}
          Everything - My Cycle
          {% elif state == "Attente du deuxième séchage" %}
          Keep thick Diapers and inserts Only (Harry Potter, Panda,
          {{- " "}} M. Potato, Cats) - Timed Dry - 30 Minutes - Medium Heat
          {% endif %}

- alias: Diaper cleaning state changed
  trigger:
    - platform: state
      entity_id: input_select.diaper_cleaning_state
      for: "01:15:00"
  condition:
    - '{{ "Attente" not in trigger.to_state.state }}'
  mode: restart
  action:
    - service: input_select.select_next
      entity_id: input_select.diaper_cleaning_state
