---
- alias: Washer leak detected
  id: Washer_leak_detected
  trigger:
    - platform: state
      entity_id: binary_sensor.washer_leak_sensor
      to: "on"
  action:
    - service: switch.turn_off
      entity_id: switch.washer_power
    - service: notify.lg_webos_smart_tv
      data:
        message: "Washing machine is leaking"
    - repeat:
        sequence:
          - service: notify.all_people
            data:
              message: "De l'eau est détectée dans le bac de la laveuse."
          - delay:
              seconds: 10
        until:
          - condition: state
            entity_id: binary_sensor.washer_leak_sensor
            state: 'off'
    - service: notify.all_people
      data:
        message: Le problème est maintenant réglé.
