---
- alias: xbox turns on
  id: xbox_turns_on
  trigger:
    - platform: state
      entity_id: binary_sensor.xbox
      to: 'on'
  action:
    - service: select.select_option
      data:
        entity_id: select.yharmony_activities
        options: "XBOX"

- alias: xbox turns off
  id: xbox_turns_off
  trigger:
    platform: state
    entity_id: binary_sensor.xbox
    to: 'off'
  condition:
    condition: state
    entity_id: select.yharmony_activities
    state: "XBOX"
  action:
    - service: select.select_option
      data:
        entity_id: select.yharmony_activities
        options: "Power Off"
