---
- platform: mqtt
  name: "leaf_battery_charging"
  state_topic: "leaf/battery/charging"
  command_topic: "leaf/command/battery"
  payload_on: "startCharging"
  state_on: "true"
  state_off: "false"
  icon: mdi:ev-station

- platform: mqtt
  name: "leaf_climate"
  command_topic: "leaf/command/climate"
  payload_on: "start"
  payload_off: "stop"
  icon: mdi:hvac
