---
- platform: template
  switches:
    bibicar_climate:
      value_template: >-
        {{ is_state('climate.bibicar_hvac_climate_system', 'heat_cool') }}
      turn_on:
        service: script.turn_on
        data:
          entity_id: script.set_tesla_climate
          variables:
            state: "on"
      turn_off:
        service: script.turn_on
        data:
          entity_id: script.set_tesla_climate
          variables:
            state: "off"
    update_leaf:
      value_template: "{{ is_state('script.update_leaf_battery', 'on') }}"
      turn_on:
        service: script.turn_on
        entity_id: script.update_leaf_battery
      turn_off:
        service: script.turn_off
        entity_id: script.update_leaf_battery
