---
- platform: template
  switches:
    bibicar_climate:
      value_template: >-
        {{ is_state('binary_sensor.tesla_climate', 'true') }}
      turn_on:
        service: script.turn_on
        data:
          entity_id: script.set_tesla_climate
          variables:
            state: "on"
      turn_off:
        service: script.turn_on
        data:
          entity_id: script.set_tesla_climate
          variables:
            state: "off"
    update_leaf:
      value_template: "{{ is_state('script.update_leaf', 'on') }}"
      turn_on:
        service: script.turn_on
        entity_id: script.update_leaf
      turn_off:
        service: script.turn_off
        entity_id: script.update_leaf
