---
- alias: Sync front window camera time
  id: sync_front_window_camera_time
  trigger:
    - platform: time
      at: '00:00:00'
    - platform: homeassistant
      event: start
  action:
    - service: shell_command.set_front_window_camera_time

- alias: Notify when motion in front yard
  id: Notify_when_motion_in_front_yard
  mode: single
  max_exceeded: silent
  trigger:
    - platform: state
      entity_id: binary_sensor.front_window_motion_detection
      to: "on"
  action:
    - service: camera.snapshot
      data:
        entity_id: camera.front_window
        filename: /media/frontwindow.jpg
    - service: notify.yan
      data:
        message: "Front yard - motion detected"
        data:
          attachment: /media/frontwindow.jpg

- alias: Set front window camera motion sensitiviy to low
  id: set_front_window_camera_motion_sensitiviy_to_low
  trigger:
    - platform: sun
      event: sunset
  action:
    - service: shell_command.camera_front_window_set_m0_sensitivity_low_template
    - service: shell_command.camera_front_window_set_m1_sensitivity_low_template
    - service: shell_command.camera_front_window_set_m2_sensitivity_low_template

- alias: Set front window camera motion sensitiviy to high
  id: set_front_window_camera_motion_sensitiviy_to_high
  trigger:
    - platform: sun
      event: sunrise
  action:
    - service: shell_command.camera_front_window_set_m0_sensitivity_high_template
    - service: shell_command.camera_front_window_set_m1_sensitivity_high_template
    - service: shell_command.camera_front_window_set_m2_sensitivity_high_template

