---
- alias: Sync garage camera time
  id: sync_garage_camera_time
  trigger:
    - platform: time
      at: '00:00:00'
    - platform: homeassistant
      event: start
  action:
    - service: shell_command.set_front_window_camera_time
