---
- alias: Light up garage camera led when motion is detected
  id: Light_up_garage_camera_led_when_motion_is_detected
  mode: queued
  trigger:
    - platform: state
      entity_id: binary_sensor.garage_motion_detection
  action:
    - service: >
        switch.turn_{{ "on" if trigger.to_state.state == "on" else "off"}}
      entity_id: switch.garage_camera_led

- alias: Sync garage camera time
  id: sync_garage_camera_time
  trigger:
    - platform: time
      at: '00:00:00'
    - platform: homeassistant
      event: start
  action:
    - service: shell_command.set_garage_camera_time

- alias: Notify when motion in garage
  id: Notify_when_motion_in_garage
  mode: single
  max_exceeded: silent
  trigger:
    - platform: state
      entity_id: binary_sensor.garage_motion_detection
      to: "on"
      for: "00:00:01"
  condition:
    - or:
        - condition: state
          entity_id: binary_sensor.garage_door
          state: "on"
        - not:
            - condition: state
              entity_id: alarm_control_panel.home_alarm
              state: 'disarmed'
  action:
    - service: camera.snapshot
      data:
        entity_id: camera.garage_camera
        filename: /media/garage.jpg
    - service: notify.yan
      data:
        message: "Garage - motion detected"
        data:
          attachment: /media/garage.jpg

- alias: Garage door button pushed
  id: Garage_door_button_pushed
  mode: single
  max_exceeded: silent
  trigger:
    - platform: state
      entity_id: input_button.garage_door
  action:
    - service: rest_command.garage_camera_output
