---
- alias: Sync parking camera time
  id: sync_parking_camera_time
  trigger:
    - platform: time
      at: '00:00:00'
    - platform: homeassistant
      event: start
  condition:
    condition: state
    entity_id: camera.parking
    state: idle
  action:
    - service: shell_command.set_parking_camera_time

- alias: Notify when motion in parking
  id: Notify_when_motion_in_parking
  mode: single
  max_exceeded: silent
  trigger:
    - platform: state
      entity_id: binary_sensor.parking_motion_detection
      to: "on"
  action:
    - delay: "00:00:08"
    - service: google_generative_ai_conversation.generate_content
      continue_on_error: true
      data:
        prompt: >-
          on these images, does the moving object appears on the property (x=1) or off the property (x=2)?
          reply with x value only.
        image_filename:
          - /pictures/parking00001.jpg
          - /pictures/parking00007.jpg
          - /pictures/parking00012.jpg
      response_variable: on_property
    - if:
        - "{{ on_property and on_property.text == '1' }}"
      then:
        - service: google_generative_ai_conversation.generate_content
          continue_on_error: true
          data:
            prompt: >-
              Briefly describe the moving object as a short single line phone notification.
            image_filename:
              - /pictures/parking00001.jpg
              - /pictures/parking00007.jpg
              - /pictures/parking00012.jpg
          response_variable: image_description
        - service: notify.yan
          data:
            message: "{{ image_description.text if image_description else 'Parking Motion detected' }}"
            attachment: /pictures/parking00007.jpg
      else:
        - service: notify.yan
          data:
            message: "no"
            attachment: /pictures/parking00007.jpg
    - delay: "00:05:00"