---
- alias: Sync parking camera time
  id: sync_parking_camera_time
  trigger:
    - platform: time
      at: '00:00:00'
    - platform: homeassistant
      event: start
  condition:
    condition: state
    entity_id: camera.parking
    state: idle
  action:
    - service: shell_command.set_parking_camera_time

- alias: Notify when motion in parking
  id: Notify_when_motion_in_parking
  mode: single
  max_exceeded: silent
  trigger:
    - platform: state
      entity_id: binary_sensor.parking_detection
      to: "on"
  condition:
    - condition: sun
      after: sunrise
      before: sunset
  action:
    - service: camera.snapshot
      data:
        entity_id: camera.parking
        filename: /media/parking.jpg
    - service: notify.yan
      data:
        message: "Parking - motion detected"
        data:
          attachment: /media/parking.jpg
