---
- alias: Sync parking camera time
  id: sync_parking_camera_time
  trigger:
    - platform: time
      at: '00:00:00'
    - platform: homeassistant
      event: start
  condition:
    condition: state
    entity_id: camera.parking
    state: idle
  action:
    - service: shell_command.set_parking_camera_time

- alias: Notify when motion in parking
  id: Notify_when_motion_in_parking
  mode: single
  max_exceeded: silent
  trigger:
    - platform: state
      entity_id: binary_sensor.parking_motion_detection
      to: "on"
  action:
    - delay: "00:00:02"
    - service: google_generative_ai_conversation.generate_content
      continue_on_error: true
      data:
        prompt: >-
          Analyze the sequence of images from a driveway camera to determine the cause of a motion alarm.
          Briefly describe any significant changes between the images.
          Your message needs to use simple words and be short enough to fit in a phone notification.
          If the image shows no objects that might have moved, reply with "no".
          If the object was not on my parking or lot, reply with "out"
        image_filename:
          - /pictures/parking00001.jpg
          - /pictures/parking00004.jpg
          - /pictures/parking00007.jpg
      response_variable: image_description
    - service: notify.yan
      data:
        message: "{{ image_description.text or 'Parking Motion detected' }}"
        data:
          attachment: /pictures/parking00004.jpg