---
- alias: Sync parking camera time
  id: sync_parking_camera_time
  trigger:
    - platform: time
      at: '00:00:00'
    - platform: homeassistant
      event: start
  condition:
    condition: state
    entity_id: camera.parking
    state: idle
  action:
    - service: shell_command.set_parking_camera_time

- alias: Notify when motion in parking
  id: Notify_when_motion_in_parking
  mode: single
  max_exceeded: silent
  trigger:
    - platform: state
      entity_id: binary_sensor.parking_detection
      to: "on"
  action:
    - service: camera.snapshot
      data:
        entity_id: camera.parking
        filename: /media/parking.jpg
    - service: google_generative_ai_conversation.generate_content
      continue_on_error: true
      data:
        prompt: >-
          In the following sequence of images from my driveway camera, describe any objects, cars,
          animals, or person that is able to move on my lot and their location.
          Focus on the most probably thing that moved last. If there is none of that,
          reponse with "no". Your message needs to be short enough to fit in a phone notification.
        image_filename:
          - /media/parking.jpg
      response_variable: image_description
    - service: notify.yan
      data:
        message: "{{ image_description.text or 'Parking Motion detected' }}"
        data:
          attachment: /media/parking.jpg
