---
- alias: Sync parking camera time
  id: sync_parking_camera_time
  trigger:
    - platform: time
      at: '00:00:00'
    - platform: homeassistant
      event: start
  condition:
    condition: state
    entity_id: camera.parking
    state: idle
  action:
    - service: shell_command.set_parking_camera_time

- alias: Notify when motion in parking
  id: Notify_when_motion_in_parking
  mode: single
  max_exceeded: silent
  trigger:
    - platform: state
      entity_id: binary_sensor.parking_detection
      to: "on"
  action:
    - service: camera.snapshot
      data:
        entity_id: camera.parking
        filename: /media/parking.jpg
    - delay: "00:00:01"
    - service: camera.snapshot
      data:
        entity_id: camera.parking
        filename: /media/parking2.jpg
    - delay: "00:00:01"
    - service: camera.snapshot
      data:
        entity_id: camera.parking
        filename: /media/parking3.jpg
    - service: google_generative_ai_conversation.generate_content
      continue_on_error: true
      data:
        prompt: >-
          Motion has been detected, compare and very briefly describe what you see
          in the following sequence of images from my driveway camera.
          What do you think caused the motion alarm? Do not describe stationary objects or
          buildings. If you see no obvious causes of motion, reply with "no".
          If the motion was not on or very near my lot, reply with "out".
          Your message needs to be short enough to fit in a phone notification.
        image_filename:
          - /media/parking.jpg
          - /media/parking2.jpg
          - /media/parking3.jpg
      response_variable: image_description
    - service: notify.yan
      data:
        message: "{{ image_description.text or 'Parking Motion detected' }}"
        data:
          attachment: /media/parking.jpg
