---
- alias: Sync parking camera time
  id: sync_parking_camera_time
  trigger:
    - platform: time
      at: '00:00:00'
    - platform: homeassistant
      event: start
  condition:
    condition: state
    entity_id: camera.parking
    state: idle
  action:
    - service: shell_command.set_parking_camera_time

- alias: Notify when motion in parking
  id: Notify_when_motion_in_parking
  mode: single
  max_exceeded: silent
  trigger:
    - trigger: mqtt
      topic: "axis/parking/motion"
  action:
    - delay: "00:00:01"
    - service: gemini_api.generate_text
      continue_on_error: true
      data:
        prompt: >-
          This is a motion alert in the front of my house.
          Summarize what you see in the sequential camera snapshots.
          If there is a person, describe what they're doing and what they look like.
          If there is a car, describe where it is, the color and makes.
          Don't describe the scene.
          Describe the thing that most probably caused the motion alert.
          The message should be short enough simple sentence that fits in a phone notification (max 8 words).
          Reply with the message only, nothing more.
        images:
          - /pictures/parking00001.jpg
          - /pictures/parking00007.jpg
      response_variable: image_description
    - service: notify.yan
      data:
        message: "{{ image_description.text if image_description else 'Parking Motion detected' }}"
        data:
          attachment: /pictures/parking00007.jpg
    - delay: "00:05:00"