---
- alias: Sync parking camera time
  id: sync_parking_camera_time
  trigger:
    - platform: time
      at: '00:00:00'
    - platform: homeassistant
      event: start
  condition:
    condition: state
    entity_id: camera.parking
    state: idle
  action:
    - service: shell_command.set_parking_camera_time

- alias: Notify when motion in parking
  id: Notify_when_motion_in_parking
  mode: single
  max_exceeded: silent
  trigger:
    - platform: state
      entity_id: binary_sensor.parking_motion_detection
      to: "on"
  action:
    - delay: "00:00:08"
    - service: google_generative_ai_conversation.generate_content
      continue_on_error: true
      data:
        prompt: >-
          Analyze the sequence of images from a driveway camera to determine the cause of a motion alarm.
          Briefly describe any changes between the images.
          Your message needs to use simple words and be short enough to fit in a phone notification.
          If the image shows nothing that have moved, reply with "no".
          If the object was on the street, reply with "out"
        image_filename:
          - /pictures/parking00001.jpg
          - /pictures/parking00006.jpg
          - /pictures/parking000012.jpg
      response_variable: image_description
    - service: notify.yan
      data:
        message: "{{ image_description.text or 'Parking Motion detected' }}"
        data:
          attachment: /pictures/parking00005.jpg
    - delay: "00:05:00"