---
- alias: Sync rear window camera time
  id: sync_rear_window_camera_time
  trigger:
    - platform: time
      at: '00:00:00'
    - platform: homeassistant
      event: start
  action:
    - service: shell_command.set_rear_window_camera_time
