---
set_hdr_mode:
  description: Activate or deactivate hdr mode of hyperhd.
  fields:
    hdr_mode:
      description: 1 to activate hdr mode, 0 otherwise.
      example: 1

apply_effect:
  description: Apply an effect to hyperhd for a specified priority.
  fields:
    effect:
      description: The name of the effect.
      example: Cinema dim lights
    priority:
      description: The priority that will be use for the effect.
      example: 120

clear_priority:
  description: Clear the effect for the specified priority.
  fields:
    priority:
      description: The priority that will be cleared.
      example: 120
