---
update_tv_state:
  description: Change the state of the tv input.
  fields:
    state:
      description: On if tv input must be activated. Off otherwise.
      example: "on"

apply_effect:
  description: Apply an effect to hyperion for a specified priority.
  fields:
    effect:
      description: The name of the effect.
      example: Cinema dim lights
    priority:
      description: The priority that will be use for the effect.
      example: 120
    args:
      description: Optional arguments to modify an effect.
      example: >-
        {
          "color-start": [238, 173, 47],
          "color-end": [136, 97, 7],
          "fade-time": 2
        }

clear_priority:
  description: Clear the effect for the specified priority.
  fields:
    priority:
      description: The priority that will be cleared.
      example: 120
