name: Test Home Assistant Config

on:
  push:
    branches:
      - master
    paths: 
      - 'hass/**'
      - '.github/workflows/**'
      - '.stubs/**'
  pull_request:
    branches: 
      - master 
    paths: 
      - 'hass/**'
      - '.github/workflows/**'
      - '.stubs/**'

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - name: Getting Home Assistant configuration
        uses: actions/checkout@v2
      - name: Running YAMLlint
        uses: docker://pipelinecomponents/yamllint:latest
        with:
          args: yamllint .
  home_assistant_current:
    runs-on: ubuntu-latest
    steps:
      - name: Getting Home Assistant configuration
        uses: actions/checkout@v2
      - name: Copy stub files into configuration folder
        run: cp -R ./.stubs/hass/* ./hass
      - name: Home Assistant Check Config
        uses: docker://homeassistant/home-assistant:0.115.0
        with:
          args: python -m homeassistant --config ./hass/ --script check_config --info all
