---
- alias: back door open turn off thermostat
  id: back_door_open_turn_off_thermostat
  trigger:
    platform: state
    entity_id: binary_sensor.back_door
    from: "off"
    to: "on"
    for: "00:03:00"
  condition:
    condition: state
    entity_id: climate.main_floor
    attribute: preset_mode
    state: Home
  action:
    - service: climate.set_preset_mode
      data:
        entity_id: climate.main_floor
        preset_mode: Away
    - wait_template: '{{ is_state("binary_sensor.back_door", "off") }}'
    - service: climate.set_preset_mode
      data:
        entity_id: climate.main_floor
        preset_mode: Home

- alias: Disarmed alarm
  trigger:
    platform: state
    entity_id: alarm_control_panel.home_alarm
    to: 'disarmed'
  action:
    - service: climate.set_preset_mode
      data:
        entity_id: climate.main_floor
        preset_mode: home
    - condition: state
      entity_id: person.cath
      state: "home"

- alias: Disarmed alarm from pending
  trigger:
    platform: state
    entity_id: alarm_control_panel.home_alarm
    from: 'pending'
    to: 'disarmed'
  condition:
    condition: or
    conditions:
      - condition: sun
        after: sunset
        after_offset: "-01:00:00"
      - condition: sun
        before: sunrise
        after_offset: "01:00:00"
  action:
    - service: light.turn_on
      data:
        entity_id: light.kitchen_main_light, light.ground_floor_hallway_light
        brightness: 50

- alias: armed away alarm
  trigger:
    platform: state
    entity_id: alarm_control_panel.home_alarm
    to: 'armed_away'
  action:
    - service: climate.set_preset_mode
      data:
        entity_id: climate.main_floor
        preset_mode: away
    - service: script.turn_on
      data:
        entity_id: script.lights_off_except
        variables:
          exclude_lights:
            - switch.light_front
    - service: remote.turn_off
      entity_id: remote.yharmony

- alias: Morning routine when waking up
  id: Morning_routine_when_waking_up
  trigger:
    platform: state
    entity_id: binary_sensor.second_floor_motion
  condition:
    - condition: time
      after: "6:00:00"
      before: "9:00:00"
  mode: single
  max_exceeded: silent
  action:
    - service: script.morning
