---
- alias: Google tv turns on
  id: google_tv_turns_on
  trigger:
    - platform: state
      entity_id: media_player.living_room_tv
  condition:
    condition: template
    value_template: >
      {{ trigger.from_state is not none and trigger.to_state is not none and
         trigger.from_state.state in ['off', 'unavailable'] and
         trigger.to_state.state in ['idle', 'playing', 'paused'] }}
  action:
    - service: switch.turn_on
      entity_id: switch.yharmony_chromecast

- alias: Google tv turns off
  id: google_tv_turns_off
  trigger:
    platform: state
    entity_id: media_player.living_room_tv
    to: 'off'
  action:
    - service: remote.turn_off
      entity_id: remote.yharmony
