---
- alias: Reconnect Hangouts
  trigger:
    - entity_id: sensor.external_ip
      platform: state
  condition:
    - '{{ trigger.from_state.state != trigger.to_state.state }}'
    - '{{ not is_state("sensor.external_ip", "unavailable") }}'
  action:
    - service: hangouts.reconnect
