- alias: Hue remote automation - Long Press Off
  trigger:
    - platform: state
      entity_id: sensor.hue_dimmer_switch_1
      to: "4_hold"
  action:
    - service: alarm_control_panel.alarm_arm_home
      entity_id: all
    - service: light.turn_off
      entity_id: all
    - service: switch.turn_off
      entity_id: group.all_light_switches
    - service: remote.turn_off
      entity_id: remote.yharmony
    - service: climate.set_preset_mode
      data:
        entity_id: climate.main_floor
        preset_mode: sleep
    - service: media_player.volume_set
      entity_id: media_player.bedroom
      data:
        volume_level: 0.05
    - service: tts.google_translate_say
      entity_id: media_player.bedroom
      data:
        message: "N'oubliez pas vos pilules et la nourriture sur le comptoir. Bonne nuit!"
        language: 'fr'

- alias: Hue remote automation - Long Press ON
  trigger:
    - platform: state
      entity_id: sensor.hue_dimmer_switch_1
      to: "1_hold"
  condition:
    condition: state
    entity_id: group.all_people
    state: "home"
  action:
    - service: alarm_control_panel.alarm_disarm
      entity_id: all
    - service: climate.set_preset_mode
      data:
        entity_id: climate.main_floor
        preset_mode: home
