---
- alias: Hue remote automation - Long Press Off
  trigger:
    - platform: event
      event_type: hue_event
      event_data:
        id: "hue_dimmer_switch_1"
        event: 4001
  action:
    - service: alarm_control_panel.alarm_arm_home
      entity_id: all
    - service: script.turn_on
      data:
        entity_id: script.lights_off_except
        variables:
          exclude_lights:
            - light.frederique_main_light
            - light.frederique_night_light
    - service: switch.turn_off
      entity_id: group.all_light_switches
    - service: remote.turn_off
      entity_id: remote.yharmony
    - service: climate.set_preset_mode
      data:
        entity_id: climate.main_floor
        preset_mode: sleep
    - service: media_player.volume_set
      entity_id: media_player.bedroom
      data:
        volume_level: 0.05
    - service: tts.google_translate_say
      entity_id: media_player.bedroom
      data:
        message: >-
          N'oubliez pas vos pilules et la nourriture sur le comptoir.
          Bonne nuit!
        language: 'fr'

- alias: Hue remote automation - Long Press ON
  trigger:
    - platform: event
      event_type: hue_event
      event_data:
        id: "hue_dimmer_switch_1"
        event: 1001
  condition:
    condition: state
    entity_id: group.all_people
    state: "home"
  action:
    - service: alarm_control_panel.alarm_disarm
      entity_id: all
    - service: climate.set_preset_mode
      data:
        entity_id: climate.main_floor
        preset_mode: home
    - service: notify.cath
      data:
        message: >-
          {%- set weekday = ['Lundi','Mardi','Mercredi','Jeudi',
                            'Vendredi','Samedi','Dimanche'] -%}
          {%- set dt = states.sensor.eve2gmmug_charge.attributes.updated_on -%}
          Bon matin Catherine!
          Ton carosse est chargé à
          {{- " " + states('sensor.eve2gmmug_charge') }}% et est
          {%- if is_state("binary_sensor.eve2gmmug_plug_status", "on") -%}
          {{ " " }}branché.
          {%- else -%}
          {{ " " }}DÉBRANCHÉ.
          {%- endif -%}
          {{ " " }}La dernière mise à jour est ce {{ weekday[dt.weekday()] -}}
          {{ " " }}à {{ dt.astimezone().strftime('%HH%M') }}.
