---
- alias: Keep hyperion on
  trigger:
    - platform: state
      entity_id: light.hyperion
      to: 'off'
  action:
    - service: light.turn_on
      data:
        entity_id: light.hyperion

- alias: Turn hyperion tv off when harmony is turned off
  trigger:
    - platform: state
      entity_id: remote.yharmony
      to: 'off'
  action:
    - service: hyperion_priority.update_tv_state
      data:
        state: "off"

- alias: Hyperion Hdmi when casting or gaming
  id: hyperion_hdmi_when_casting
  trigger:
    - platform: state
      entity_id: switch.yharmony_chromecast
      to: "on"
    - platform: state
      entity_id: switch.yharmony_nintendo
      to: "on"
  mode: restart
  action:
    # show running dots like a loading effect
    # instead of glitchy lights when starting up the system.
    - service: hyperion_priority.apply_effect
      data:
        effect: Lights
        priority: 130
    # 15 seconds is the time for the whole system to be ready.
    - delay: "00:00:15"
    - service: hyperion_priority.clear_priority
      data:
        priority: 130
    - or:
        - condition: state
          entity_id: switch.yharmony_chromecast
          state: "on"
        - condition: state
          entity_id: switch.yharmony_nintendo
          state: "on"
    - service: hyperion_priority.update_tv_state
      data:
        state: "on"

- alias: Hyperion pausing chromecast
  trigger:
    - platform: state
      entity_id: media_player.living_room_tv
      from: "playing"
      to: "paused"
  action:
    - service: hyperion_priority.apply_effect
      data:
        effect: Cinema brighten lights
        priority: 130
        args: >-
          {
            "color-start": [136, 97, 7],
            "color-end": [238, 173, 47],
            "fade-time": 2
          }
- alias: Hyperion playing chromecast
  trigger:
    - platform: state
      entity_id: media_player.living_room_tv
      from: "paused"
  action:
    - service: hyperion_priority.apply_effect
      data:
        effect: Cinema dim lights
        priority: 130
        args: >-
          {
            "color-start": [238, 173, 47],
            "color-end": [136, 97, 7],
            "fade-time": 2
          }
    - delay: "00:00:02"
    - service: hyperion_priority.clear_priority
      data:
        priority: 130

- alias: Hyperion phone ringing
  trigger:
    - platform: state
      entity_id: input_boolean.yan_phone_rings
    - platform: state
      entity_id: input_boolean.cath_phone_rings
  variables:
    effect_priority: >-
      {% if trigger.entity_id == "input_boolean.yan_phone_rings" %}
        120
      {% else %}
        119
      {% endif %}
  action:
    - if:
        - '{{ trigger.to_state.state == "on" }}'
      then:
        - service: hyperion_priority.apply_effect
          data:
            effect: >-
              {% if trigger.entity_id == "input_boolean.yan_phone_rings" %}
                Police Lights Solid
              {% else %}
                Rainbow swirl fast
              {% endif %}
            priority: '{{ effect_priority }}'
      else:
        - service: hyperion_priority.clear_priority
          data:
            priority: '{{ effect_priority }}'

- alias: Hyperion phone notification
  trigger:
    - platform: state
      entity_id: input_boolean.yan_phone_notification
    - platform: state
      entity_id: input_boolean.cath_phone_notification
  variables:
    notification_color: >-
      {% if trigger.entity_id == "input_boolean.yan_phone_notification" %}
        [0, 255, 0]
      {% else %}
        [190, 0, 255]
      {% endif %}
    effect_priority: >-
      {% if trigger.entity_id == "input_boolean.yan_phone_notification" %}
        126
      {% else %}
        124
      {% endif %}
  mode: queued
  action:
    - repeat:
        count: 2
        sequence:
          - service: hyperion_priority.apply_effect
            data:
              effect: Cinema brighten lights
              args: >
                { "color-start": [0, 0, 0],
                  "color-end": {{ notification_color }},
                  "fade-time": 0.8 }
              priority: '{{ effect_priority }}'
          - delay: "00:00:01"
          - service: hyperion_priority.apply_effect
            data:
              effect: Cinema dim lights
              args: >
                { "color-start": {{ notification_color }},
                  "color-end": [0, 0, 0],
                  "fade-time": 0.8 }
              priority: '{{ effect_priority }}'
          - delay: "00:00:01"
    - service: hyperion_priority.clear_priority
      data:
        priority: '{{ effect_priority }}'
