---
- alias: Turn on front light at sunset
  trigger:
    - platform: sun
      event: sunset
  action:
    service: switch.turn_on
    entity_id: switch.light_front

- alias: Turn on front light in the morning
  trigger:
    - platform: time
      at: '05:30:00'
  condition:
    condition: sun
    before: sunrise
  action:
    service: switch.turn_on
    entity_id: switch.light_front

- alias: Turn off front light at 10pm or sunrise
  trigger:
    - platform: time
      at: '22:00:00'
    - platform: sun
      event: sunrise
  action:
    service: switch.turn_off
    entity_id: switch.light_front

- alias: turn off entrance light when exiting
  id: turn_off_entrance_light_when_exiting
  trigger:
    - platform: event
      event_type: zwave_js_notification
      event_data:
        device_id: "57d85ed64f414f701c2a5468be4f9d42"
        event_label: "Keypad lock operation"
  action:
    - service: light.turn_off
      entity_id: switch.entrance_light

- alias: turn on entrance light when entering
  trigger:
    - platform: event
      event_type: zwave_js_notification
      event_data:
        device_id: "57d85ed64f414f701c2a5468be4f9d42"
        event_label: "Keypad unlock operation"
  condition:
    condition: or
    conditions:
      - condition: sun
        after: sunset
        after_offset: "-01:00:00"
      - condition: sun
        before: sunrise
        after_offset: "01:00:00"
  action:
    - service: script.turn_on
      data:
        entity_id: script.auto_switch_on
        variables:
          duration_seconds: 300
          auto_entity: switch.entrance_light

- alias: Update christmas lights
  trigger:
    - platform: state
      entity_id: person.cath
    - platform: state
      entity_id: alarm_control_panel.home_alarm
  action:
    - service: >
        {% if is_state('person.cath', 'home') and
           is_state('alarm_control_panel.home_alarm', 'disarmed') %}
          light.turn_on
        {% else %}
          light.turn_off
        {% endif %}
      entity_id: light.twinkly_a80df9

- alias: Turn on second floor hallway lights when motion is detected
  id: Turn_on_second_floor_hallway_lights_when_motion_is_detected
  trigger:
    - platform: state
      entity_id: binary_sensor.second_floor_motion
      to: "on"
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: light.second_floor_hallway_light
          state: "off"
        - condition: state
          entity_id: light.second_floor_hallway_light
          attribute: brightness
          state: 103
  mode: restart
  action:
    - service: light.turn_on
      data:
        entity_id: light.second_floor_hallway_light
        brightness: 103
    - wait_for_trigger:
        - platform: state
          entity_id: light.second_floor_hallway_light
      timeout:
        minutes: 2
    - condition: template
      value_template: "{{ wait.trigger is none }}"
    - service: light.turn_off
      entity_id: light.second_floor_hallway_light
