---
- alias: Cath leaving home
  trigger:
    - platform: zone
      entity_id: person.cath
      zone: zone.home
      event: leave
  action:
    service: light.turn_off
    entity_id:
      - light.table_de_chevet_de_cath
      - light.frederique_main_light

- alias: Yan leaving work
  trigger:
    platform: zone
    entity_id: person.yan
    zone: zone.Work_yan
    event: leave
  condition:
    - condition: time
      after: !secret yan_leave_work_time
      before: '23:00:00'
  action:
    service: notify.cath
    data:
      message: >
        Yan est parti du travail. Il faut
        {{ states('sensor.yantohome') }} minutes pour rentrer à la maison.

- alias: Cath leaving work
  trigger:
    - platform: zone
      entity_id: person.cath
      zone: zone.work_cath
      event: leave
  action:
    service: notify.yan
    data:
      message: >
        Cath est parti du travail. Il faut
        {{ states('sensor.cathtohome') }} minutes pour rentrer à la maison.
