---
# ------------------------------
# zwave_js_value_notification
# trigger.event.data.property_key_name 001 (up) 002 (down)
# trigger.event.data.value KeyHeldDown KeyPressed KeyPressed2x KeyPressed3x
# trigger.event.data.device_id
# ------------------------------
- alias: Frederique main light brightness
  trigger:
    - platform: state
      entity_id: light.frederique_main_light
      attribute: brightness
  mode: restart
  action:
    repeat:
      sequence:
        - service: light.turn_on
          data:
            entity_id: light.frederique_night_light
            brightness: >-
              {{ state_attr('light.frederique_main_light', 'brightness')|int(0) }}
        - delay:
            milliseconds: 500
      until: >-
        {{ (state_attr('light.frederique_night_light', 'brightness')|int(0))
           ==
           (state_attr('light.frederique_main_light', 'brightness')|int(0)) }}

- alias: Frederique main light triple up
  trigger:
    - platform: event
      event_type: zwave_js_value_notification
      event_data:
        device_id: "{{ device_id('light.frederique_main_light') }}"
        property_key_name: "001"
        value: "KeyPressed3x"
  action:
    - service: light.turn_on
      data:
        entity_id: light.frederique_night_light
        brightness: 255

- alias: Frederique main light triple down
  trigger:
    - platform: event
      event_type: zwave_js_value_notification
      event_data:
        device_id: "{{ device_id('light.frederique_main_light') }}"
        property_key_name: "002"
        value: "KeyPressed3x"
  action:
    - service: light.turn_off
      data:
        entity_id:
          - light.frederique_night_light
          - light.frederique_main_light

- alias: Stairs double down
  trigger:
    - platform: event
      event_type: zwave_js_value_notification
      event_data:
        device_id: "{{ device_id('light.upper_stairs_light') }}"
        property_key_name: "002"
        value: "KeyPressed2x"
    - platform: event
      event_type: zwave_js_value_notification
      event_data:
        device_id: "{{ device_id('light.ground_floor_hallway_light') }}"
        property_key_name: "002"
        value: "KeyPressed2x"
  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.table_de_chevet_de_cath
          - light.table_de_chevet_de_yan
        brightness: 150

- alias: Frederique main light double down
  trigger:
    - platform: event
      event_type: zwave_js_value_notification
      event_data:
        device_id: "{{ device_id('light.frederique_main_light') }}"
        property_key_name: "002"
        value: "KeyPressed2x"
  action:
    - service: light.turn_off
      data:
        entity_id:
          - light.frederique_main_light
          - light.frederique_night_light
    - service: switch.turn_on
      data:
        entity_id: switch.baby_monitor

- alias: Frederique main light single up or release from hold up
  trigger:
    - platform: event
      event_type: zwave_js_value_notification
      event_data:
        device_id: "{{ device_id('light.frederique_main_light') }}"
        property_key_name: "001"
        value: "KeyPressed"
    - platform: event
      event_type: zwave_js_value_notification
      event_data:
        device_id: "{{ device_id('light.frederique_main_light') }}"
        property_key_name: "001"
        value: "KeyHeldDown"
  mode: single
  max_exceeded: silent
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.baby_monitor

- alias: Set zwave light to default when single click up
  trigger:
    - platform: event
      event_type: zwave_js_value_notification
      event_data:
        value: "KeyPressed"
        property_key_name: "001"
  variables:
    light_entity_id: >-
      {{ device_entities(trigger.event.data.device_id) | first }}
  condition: '{{ states(light_entity_id) != "unknown" }}'
  action:
    - service: light.turn_on
      data:
        entity_id: '{{ light_entity_id }}'
        brightness: >-
          {% if light_entity_id in
                states.group.zwave_dimmers_default_low.attributes.entity_id %}
            1
          {% else %}
            255
          {% endif %}
    - service: zwave_js.refresh_value
      data:
        entity_id: '{{ light_entity_id }}'

- alias: Bathroom ceiling light single click up
  trigger:
    - platform: event
      event_type: zwave_js_value_notification
      event_data:
        device_id: "{{ device_id('light.bathroom_ceiling_light') }}"
        property_key_name: "001"
        value: "KeyPressed"
  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.bathroom_ceiling_light
          - light.bathroom_mirror_light
        brightness: 255
    - service: switch.turn_on
      data:
        entity_id: switch.master_bathroom_fan

- alias: bathroom any light single click down
  trigger:
    - platform: event
      event_type: zwave_js_value_notification
      event_data:
        device_id: "{{ device_id('light.bathroom_ceiling_light') }}"
        property_key_name: "002"
        value: "KeyPressed"
    - platform: event
      event_type: zwave_js_value_notification
      event_data:
        device_id: "{{ device_id('light.bathroom_mirror_light') }}"
        property_key_name: "002"
        value: "KeyPressed"
  action:
    - service: light.turn_off
      entity_id:
        - light.bathroom_ceiling_light
        - light.bathroom_mirror_light
    - service: script.turn_on
      data:
        entity_id: script.auto_switch_off
        variables:
          auto_switch_entity: switch.master_bathroom_fan
          duration_seconds: 600

- alias: bathroom fan double click up
  trigger:
    - platform: event
      event_type: zwave_js_value_notification
      event_data:
        device_id: "{{ device_id('switch.master_bathroom_fan') }}"
        property_key_name: "001"
        value: "KeyPressed2x"
  action:
    - service: script.turn_on
      data:
        entity_id: script.auto_switch_on
        variables:
          auto_switch_entity: switch.master_bathroom_fan
          duration_seconds: 600

- alias: bathroom fan triple click up
  trigger:
    - platform: event
      event_type: zwave_js_value_notification
      event_data:
        device_id: "{{ device_id('switch.master_bathroom_fan') }}"
        property_key_name: "001"
        value: "KeyPressed3x"
  action:
    - service: script.turn_on
      data:
        entity_id: script.auto_switch_on
        variables:
          auto_switch_entity: switch.master_bathroom_fan
          duration_seconds: 900

- alias: bathroom any light double click up
  trigger:
    - platform: event
      event_type: zwave_js_value_notification
      event_data:
        device_id: "{{ device_id('light.bathroom_ceiling_light') }}"
        property_key_name: "001"
        value: "KeyPressed2x"
    - platform: event
      event_type: zwave_js_value_notification
      event_data:
        device_id: "{{ device_id('light.bathroom_mirror_light') }}"
        property_key_name: "001"
        value: "KeyPressed2x"
  variables:
    light_entity_id: >-
      {{ device_entities(trigger.event.data.device_id) | first }}
  condition: '{{ states(light_entity_id) != "unknown" }}'
  action:
    - service: light.turn_on
      data:
        entity_id: '{{ light_entity_id }}'
        brightness: 255

- alias: bathroom ceiling tripple click down
  trigger:
    - platform: event
      event_type: zwave_js_value_notification
      event_data:
        device_id: "{{ device_id('light.bathroom_ceiling_light') }}"
        property_key_name: "002"
        value: "KeyPressed3x"
  action:
    - service: light.turn_off
      entity_id:
        - light.bathroom_ceiling_light
        - light.bathroom_mirror_light
    - service: switch.turn_off
      entity_id: switch.master_bathroom_fan
    - service: light.turn_on
      data:
        entity_id:
          - light.kitchen_main_light
          - light.upper_stairs_light
        brightness: 40

- alias: bathroom any light double click down
  id: bathroom_any_light_double_click_down
  trigger:
    - platform: event
      event_type: zwave_js_value_notification
      event_data:
        device_id: "{{ device_id('light.bathroom_ceiling_light') }}"
        property_key_name: "002"
        value: "KeyPressed2x"
    - platform: event
      event_type: zwave_js_value_notification
      event_data:
        device_id: "{{ device_id('light.bathroom_mirror_light') }}"
        property_key_name: "002"
        value: "KeyPressed2x"
  variables:
    light_entity_id: >-
      {{ device_entities(trigger.event.data.device_id) | first }}
  condition: '{{ states(light_entity_id) != "unknown" }}'
  action:
    - service: light.turn_off
      data:
        entity_id: '{{ light_entity_id }}'

- alias: front light double click down
  trigger:
    - platform: event
      event_type: zwave_js_value_notification
      event_data:
        device_id: "{{ device_id('switch.light_front') }}"
        property_key_name: "002"
        value: "KeyPressed2x"
  action:
    - service: light.turn_off
      entity_id:
        - light.kitchen_main_light
        - light.upper_stairs_light
